language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - find . -type f -name "*.py" -not -path './venv*' | xargs pylint --rcfile=pylint.cfg
  - coverage run --source=. -m pytest
after_success:
    - coveralls
