"""empty message

Revision ID: 41d7166297d9
Revises: 857c63e3e734
Create Date: 2023-03-08 13:23:29.692967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41d7166297d9'
down_revision = '857c63e3e734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.INTEGER(),
               type_=sa.DECIMAL(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.DECIMAL(),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
